// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hearbeatConnect.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type OutputRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutputRequest) Reset()         { *m = OutputRequest{} }
func (m *OutputRequest) String() string { return proto.CompactTextString(m) }
func (*OutputRequest) ProtoMessage()    {}
func (*OutputRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ea1eaa9328fbd1a, []int{0}
}

func (m *OutputRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutputRequest.Unmarshal(m, b)
}
func (m *OutputRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutputRequest.Marshal(b, m, deterministic)
}
func (m *OutputRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutputRequest.Merge(m, src)
}
func (m *OutputRequest) XXX_Size() int {
	return xxx_messageInfo_OutputRequest.Size(m)
}
func (m *OutputRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OutputRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OutputRequest proto.InternalMessageInfo

func (m *OutputRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the greetings
type OutputReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutputReply) Reset()         { *m = OutputReply{} }
func (m *OutputReply) String() string { return proto.CompactTextString(m) }
func (*OutputReply) ProtoMessage()    {}
func (*OutputReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ea1eaa9328fbd1a, []int{1}
}

func (m *OutputReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutputReply.Unmarshal(m, b)
}
func (m *OutputReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutputReply.Marshal(b, m, deterministic)
}
func (m *OutputReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutputReply.Merge(m, src)
}
func (m *OutputReply) XXX_Size() int {
	return xxx_messageInfo_OutputReply.Size(m)
}
func (m *OutputReply) XXX_DiscardUnknown() {
	xxx_messageInfo_OutputReply.DiscardUnknown(m)
}

var xxx_messageInfo_OutputReply proto.InternalMessageInfo

func (m *OutputReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*OutputRequest)(nil), "proto.OutputRequest")
	proto.RegisterType((*OutputReply)(nil), "proto.OutputReply")
}

func init() { proto.RegisterFile("hearbeatConnect.proto", fileDescriptor_3ea1eaa9328fbd1a) }

var fileDescriptor_3ea1eaa9328fbd1a = []byte{
	// 149 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcd, 0x48, 0x4d, 0x2c,
	0x4a, 0x4a, 0x4d, 0x2c, 0x71, 0xce, 0xcf, 0xcb, 0x4b, 0x4d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xca, 0x5c, 0xbc, 0xfe, 0xa5, 0x25, 0x05, 0xa5, 0x25, 0x41,
	0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x42, 0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x8c,
	0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x92, 0x3a, 0x17, 0x37, 0x4c, 0x51, 0x41, 0x4e, 0xa5,
	0x90, 0x04, 0x17, 0x7b, 0x6e, 0x6a, 0x71, 0x71, 0x62, 0x3a, 0x4c, 0x15, 0x8c, 0x6b, 0xe4, 0xc1,
	0xc5, 0xe3, 0x91, 0x98, 0x97, 0x92, 0x93, 0x0a, 0x51, 0x2e, 0x64, 0xc1, 0xc5, 0x15, 0x9c, 0x9a,
	0x97, 0x02, 0xe5, 0x89, 0x40, 0xac, 0xd6, 0x43, 0xb1, 0x50, 0x4a, 0x08, 0x4d, 0xb4, 0x20, 0xa7,
	0x52, 0x89, 0x21, 0x89, 0x0d, 0x2c, 0x68, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xba, 0x65, 0x1f,
	0x9d, 0xbe, 0x00, 0x00, 0x00,
}
